apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aaa

resources:
  - deployment.yaml
  - service.yaml
  - route.yaml

images:
  - name: jaeger
    newName: jaegertracing/all-in-one
    newTag: '1.35'
