apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aaa

resources:
  - deployment.yaml
  - service.yaml
  - route.yaml

containers:
  - name: jaeger-all-in-one
    image: jaegertracing/all-in-one:1.35
