apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  selector:
    app: jaeger
  ports:
    - port: 80
      targetPort: 16686
    - port: 4317
      targetPort: 4317
    - port: 4318
      targetPort: 4318
