apiVersion: apps/v1
kind: Deployment
metadata:
  name: openliberty
spec:
  selector:
    matchLabels:
      app: openliberty
  replicas: 1
  template:
    metadata:
      labels:
        app: openliberty
    spec:
      containers:
        - name: openliberty
          image: otel-ol
          env:
            - name: OTEL_SERVICE_NAME
              value: otel-ol
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.version=1.0-SNAPSHOT
          envFrom:
            - configMapRef:
                name: database-config
            - configMapRef:
                name: opentelemetry
          ports:
            - name: web
              protocol: TCP
              containerPort: 9080
