apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aaa-otel-apps

commonLabels:
  app: openliberty

resources:
  - namespace.yaml
  - configMap.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

images:
  - name: otel-ol
    newName: otel-ol
    newTag: 'latest'
