kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: openliberty
spec:
  host: ol-aaa.apps.lab.ocp.lan
  to:
    kind: Service
    name: openliberty
    weight: 100
  port:
    targetPort: 9080
  wildcardPolicy: None
