apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
  selector:
    matchLabels:
      app: nodejs
  replicas: 1
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs
          image: nodejs
          env:
            - name: OTLP_URL
              value: 'http://jaeger.aaa-jaeger.svc.cluster.local:4318/v1/traces'
            - name: SERVICE_NAME
              value: otel-nodejs
            - name: SERVICE_VERSION
              value: '0.2.0'
          ports:
            - containerPort: 8080
