apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aaa-otel-apps

commonLabels:
  app: nodejs

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

images:
  - name: nodejs
    newName: nodejs
    newTag: 'latest'
