FROM registry.redhat.io/rhel8/nodejs-22-minimal:1-9.1741811151

RUN npm install express
RUN chown -R 1001:0 ${HOME}/.npm
RUN chmod -R g+w ${HOME}/.npm

#RUN npm install express && \
#    chown -R 1001:0 ${HOME}/.npm && \
#    chmod -R g+w ${HOME}/.npm

COPY ./*.js ./package.json ${HOME}/ 

ENTRYPOINT ["npm"]
CMD ["run", "start"]
