apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aaa-otel-apps

commonLabels:
  app: spring

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml

images:
  - name: otel-spring
    newName: otel-spring
    newTag: latest
