kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: spring
spec:
  host: ol-spring-aaa.apps.lab.ocp.lan
  to:
    kind: Service
    name: spring
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
