apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318
          grpc:
            endpoint: 0.0.0.0:4317
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 50
        spike_limit_percentage: 30
      batch:
        timeout: 5s
      resource:
        attributes:
        - key: test.key
          value: "test-value"
          action: insert
    exporters:
      logging:
        loglevel: info
      otlp:
        endpoint: jaeger.aaa-jeager.svc.cluster.local:4317
    extensions:
      health_check:
    service:
      extensions:
      - health_check
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
    #          processors: [memory_limiter, batch, resource]
    #          exporters: [logging, otlp]
          exporters: [otlp]
