apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318
          grpc:
            endpoint: 0.0.0.0:4317
    processors:
      batch:
        timeout: 5s
      resource:
        attributes:
        - key: test.key
          value: "test-value"
          action: insert
    exporters:
      logging:
        loglevel: info
      jaeger:
        endpoint: jaeger.aaa-jeager.svc.cluster.local:14250
    extensions:
      health_check:
    service:
      extensions:
      - health_check
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch, resource]
          exporters: [logging, jaeger]
