apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector
spec:
  selector:
    matchLabels:
      app: collector
  replicas: 1
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
      - name: collector
        image: collector
        livenessProbe:
          httpGet:
            path: /
            port: 13133
          initialDelaySeconds: 30
          periodSeconds: 30
        volumeMounts:
        - name: config
          mountPath: /etc/otelcol-contrib
          readOnly: true
        ports:
        - name: otlp-grpc
          protocol: TCP
          containerPort: 4317
        - name: otlp-http
          protocol: TCP
          containerPort: 4318
        - name: metrics
          protocol: TCP
          containerPort: 8888
      volumes:
      - name: config
        configMap:
          name: collector-config
