apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aaa-otel-collector

commonLabels:
  app: collector

resources:
- namespace.yaml
- configMap.yaml
- deployment.yaml
- service.yaml
- service-monitor.yaml

images:
- name: collector
  newName: registry.redhat.io/rhosdt/opentelemetry-collector-rhel8@sha256:526b5140e13e6adbb5e9f4a1333c4017bbd9595001f2d39c4e1452e1e1f9e7ca
#  newName: otel/opentelemetry-collector-contrib
#  newTag: 'latest'
