apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aaa-otel-collector

commonLabels:
  app: collector

resources:
- namespace.yaml
- configMap.yaml
- deployment.yaml
- service.yaml
- service-monitor.yaml

images:
- name: collector
  newName: otel/opentelemetry-collector-contrib
  newTag: 'latest'
