apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: openshift-operators
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 50
        spike_limit_percentage: 30
      batch:
        timeout: 5s
      resource:
        attributes:
        - key: test.key
          value: "test-value"
          action: insert
    exporters:
      jaeger:
        endpoint: jaeger.aaa-jaeger.svc.cluster.local:14250
        tls:
          insecure: true
      logging:
        loglevel: info
    extensions:
      health_check: {}
    service:
      extensions:
        - health_check
      pipelines:
        traces:
          receivers:
            - otlp
          processors:
            - memory_limiter
            - batch
          exporters:
            - jaeger
            - logging

